//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAcademiaWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoAcademiaWPF.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você deseja fechar essa janela ?.
        /// </summary>
        public static string confirmacaoFecharAplicacao {
            get {
                return ResourceManager.GetString("confirmacaoFecharAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura (cm):.
        /// </summary>
        public static string labelAltura {
            get {
                return ResourceManager.GetString("labelAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Dir. (cm):.
        /// </summary>
        public static string labelAntebracoD {
            get {
                return ResourceManager.GetString("labelAntebracoD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Esq. (cm):.
        /// </summary>
        public static string labelAntebracoE {
            get {
                return ResourceManager.GetString("labelAntebracoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro:.
        /// </summary>
        public static string labelBairro {
            get {
                return ResourceManager.GetString("labelBairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bíceps Dir. (cm):.
        /// </summary>
        public static string labelBicepsD {
            get {
                return ResourceManager.GetString("labelBicepsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bíceps Esq. (cm):.
        /// </summary>
        public static string labelBicepsE {
            get {
                return ResourceManager.GetString("labelBicepsE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP:.
        /// </summary>
        public static string labelCEP {
            get {
                return ResourceManager.GetString("labelCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade:.
        /// </summary>
        public static string labelCidade {
            get {
                return ResourceManager.GetString("labelCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cintura (cm):.
        /// </summary>
        public static string labelCintura {
            get {
                return ResourceManager.GetString("labelCintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento:.
        /// </summary>
        public static string labelComplemento {
            get {
                return ResourceManager.GetString("labelComplemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Dir. (cm):.
        /// </summary>
        public static string labelCoxaD {
            get {
                return ResourceManager.GetString("labelCoxaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Esq. (cm):.
        /// </summary>
        public static string labelCoxaE {
            get {
                return ResourceManager.GetString("labelCoxaE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF:.
        /// </summary>
        public static string labelCPF {
            get {
                return ResourceManager.GetString("labelCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF do Aluno:.
        /// </summary>
        public static string labelCPFAluno {
            get {
                return ResourceManager.GetString("labelCPFAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF do Colaborador:.
        /// </summary>
        public static string labelCPFColaborador {
            get {
                return ResourceManager.GetString("labelCPFColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Admissão:.
        /// </summary>
        public static string labelDataAdmissao {
            get {
                return ResourceManager.GetString("labelDataAdmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Fim:.
        /// </summary>
        public static string labelDataFim {
            get {
                return ResourceManager.GetString("labelDataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data e Hora:.
        /// </summary>
        public static string labelDataHora {
            get {
                return ResourceManager.GetString("labelDataHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Início:.
        /// </summary>
        public static string labelDataInicio {
            get {
                return ResourceManager.GetString("labelDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nascimento:.
        /// </summary>
        public static string labelDataNascimento {
            get {
                return ResourceManager.GetString("labelDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email:.
        /// </summary>
        public static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada:.
        /// </summary>
        public static string labelEntrada {
            get {
                return ResourceManager.GetString("labelEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID:.
        /// </summary>
        public static string labelID {
            get {
                return ResourceManager.GetString("labelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Aluno:.
        /// </summary>
        public static string labelIDAluno {
            get {
                return ResourceManager.GetString("labelIDAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Atendente:.
        /// </summary>
        public static string labelIDAtendente {
            get {
                return ResourceManager.GetString("labelIDAtendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Instrutor:.
        /// </summary>
        public static string labelIDInstrutor {
            get {
                return ResourceManager.GetString("labelIDInstrutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IMC:.
        /// </summary>
        public static string labelIMC {
            get {
                return ResourceManager.GetString("labelIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Laudo Médico:.
        /// </summary>
        public static string labelLaudoMedico {
            get {
                return ResourceManager.GetString("labelLaudoMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro:.
        /// </summary>
        public static string labelLogradouro {
            get {
                return ResourceManager.GetString("labelLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Gorda (kg):.
        /// </summary>
        public static string labelMassaGorda {
            get {
                return ResourceManager.GetString("labelMassaGorda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Massa Magra (kg):.
        /// </summary>
        public static string labelMassaMagra {
            get {
                return ResourceManager.GetString("labelMassaMagra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome:.
        /// </summary>
        public static string labelNome {
            get {
                return ResourceManager.GetString("labelNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número:.
        /// </summary>
        public static string labelNumero {
            get {
                return ResourceManager.GetString("labelNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivo:.
        /// </summary>
        public static string labelObjetivo {
            get {
                return ResourceManager.GetString("labelObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações:.
        /// </summary>
        public static string labelObservacoes {
            get {
                return ResourceManager.GetString("labelObservacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações da Restrição:.
        /// </summary>
        public static string labelObservacoesRestricao {
            get {
                return ResourceManager.GetString("labelObservacoesRestricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País:.
        /// </summary>
        public static string labelPais {
            get {
                return ResourceManager.GetString("labelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Dir. (cm):.
        /// </summary>
        public static string labelPanturrilhaD {
            get {
                return ResourceManager.GetString("labelPanturrilhaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Esq. (cm):.
        /// </summary>
        public static string labelPanturrilhaE {
            get {
                return ResourceManager.GetString("labelPanturrilhaE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual de Gordura (%):.
        /// </summary>
        public static string labelPercentualGordura {
            get {
                return ResourceManager.GetString("labelPercentualGordura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso (kg):.
        /// </summary>
        public static string labelPeso {
            get {
                return ResourceManager.GetString("labelPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso Ideal (kg):.
        /// </summary>
        public static string labelPesoIdeal {
            get {
                return ResourceManager.GetString("labelPesoIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano:.
        /// </summary>
        public static string labelPlano {
            get {
                return ResourceManager.GetString("labelPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadril (cm):.
        /// </summary>
        public static string labelQuadril {
            get {
                return ResourceManager.GetString("labelQuadril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Repetir Senha:.
        /// </summary>
        public static string labelReSenha {
            get {
                return ResourceManager.GetString("labelReSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restrição Médica.
        /// </summary>
        public static string labelRestricaoMedica {
            get {
                return ResourceManager.GetString("labelRestricaoMedica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saída:.
        /// </summary>
        public static string labelSaida {
            get {
                return ResourceManager.GetString("labelSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha:.
        /// </summary>
        public static string labelSenha {
            get {
                return ResourceManager.GetString("labelSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha do Colaborador:.
        /// </summary>
        public static string labelSenhaColaborador {
            get {
                return ResourceManager.GetString("labelSenhaColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone:.
        /// </summary>
        public static string labelTelefone {
            get {
                return ResourceManager.GetString("labelTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo:.
        /// </summary>
        public static string labelTipo {
            get {
                return ResourceManager.GetString("labelTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tórax (cm):.
        /// </summary>
        public static string labelTorax {
            get {
                return ResourceManager.GetString("labelTorax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF:.
        /// </summary>
        public static string labelUF {
            get {
                return ResourceManager.GetString("labelUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vinculo:.
        /// </summary>
        public static string labelVinculo {
            get {
                return ResourceManager.GetString("labelVinculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frequência.
        /// </summary>
        public static string textFrequencia {
            get {
                return ResourceManager.GetString("textFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        public static string textMatricula {
            get {
                return ResourceManager.GetString("textMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Aluno.
        /// </summary>
        public static string tituloCadastrarAluno {
            get {
                return ResourceManager.GetString("tituloCadastrarAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Aula.
        /// </summary>
        public static string tituloCadastrarAula {
            get {
                return ResourceManager.GetString("tituloCadastrarAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Avaliação.
        /// </summary>
        public static string tituloCadastrarAvaliacao {
            get {
                return ResourceManager.GetString("tituloCadastrarAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Colaborador.
        /// </summary>
        public static string tituloCadastrarColaborador {
            get {
                return ResourceManager.GetString("tituloCadastrarColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Frequência.
        /// </summary>
        public static string tituloCadastrarFrequencia {
            get {
                return ResourceManager.GetString("tituloCadastrarFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Logradouro.
        /// </summary>
        public static string tituloCadastrarLogradouro {
            get {
                return ResourceManager.GetString("tituloCadastrarLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Matrícula.
        /// </summary>
        public static string tituloCadastrarMatricula {
            get {
                return ResourceManager.GetString("tituloCadastrarMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Senha.
        /// </summary>
        public static string tituloCadastrarSenha {
            get {
                return ResourceManager.GetString("tituloCadastrarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Treino.
        /// </summary>
        public static string tituloCadastrarTreino {
            get {
                return ResourceManager.GetString("tituloCadastrarTreino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Janela Home.
        /// </summary>
        public static string tituloConfirmacao {
            get {
                return ResourceManager.GetString("tituloConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        public static string tituloLogin {
            get {
                return ResourceManager.GetString("tituloLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Academia.
        /// </summary>
        public static string tituloPrincipal {
            get {
                return ResourceManager.GetString("tituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno.
        /// </summary>
        public static string txtAluno {
            get {
                return ResourceManager.GetString("txtAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aulas.
        /// </summary>
        public static string txtAulas {
            get {
                return ResourceManager.GetString("txtAulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliação.
        /// </summary>
        public static string txtAvaliacao {
            get {
                return ResourceManager.GetString("txtAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string txtCancelar {
            get {
                return ResourceManager.GetString("txtCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador.
        /// </summary>
        public static string txtColaborador {
            get {
                return ResourceManager.GetString("txtColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        public static string txtConfiguracoes {
            get {
                return ResourceManager.GetString("txtConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Principal.
        /// </summary>
        public static string txtHome {
            get {
                return ResourceManager.GetString("txtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        public static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login/Loggout.
        /// </summary>
        public static string txtLoginLoggout {
            get {
                return ResourceManager.GetString("txtLoginLoggout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string txtLogradouro {
            get {
                return ResourceManager.GetString("txtLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string txtSalvar {
            get {
                return ResourceManager.GetString("txtSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione o Idioma.
        /// </summary>
        public static string txtSelecionarIdioma {
            get {
                return ResourceManager.GetString("txtSelecionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string txtSenha {
            get {
                return ResourceManager.GetString("txtSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Treinos.
        /// </summary>
        public static string txtTreinos {
            get {
                return ResourceManager.GetString("txtTreinos", resourceCulture);
            }
        }
    }
}
